version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: qs_ranking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    ports:
      - "5433:5432"  # Maps host port 5433 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck: # Recommended: Add a healthcheck for the database
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy # Ensure DB is ready before starting Django

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - "8080:80"
    # depends_on:
    #   - web # Client depends on the web service to be up

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Map host port 80 to Nginx container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your Nginx config read-only
    depends_on:
      - web # Nginx depends on the web service to be up

volumes:
  db_data: